"""Learned eviction policy.

For every candidate page in a full cache we compute 4 simple features
  - recency       : log(1 + time since last access)
  - window freq   : accesses in the last WINDOW references
  - total count   : log(1 + accesses so far)
  - residency age : log(1 + time since the page was loaded)
and a classifier predicts label 1 = "good to evict" (page is NOT reused
within the next T_HORIZON references).  Labels come from hindsight
(the future of the trace), as in Belady's algorithm.  The page with the
highest predicted probability is evicted.

Variants
  * static  : trained once offline, never updated  (DT or LR)
  * online  : decision tree retrained periodically on recent, already
              matured eviction snapshots (adaptive layer)
"""
import bisect
from collections import deque, Counter
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from policies import Policy, simulate

T_HORIZON = 64
WINDOW = 200


def make_model(kind):
    if kind == "dt":
        return DecisionTreeClassifier(max_depth=4, min_samples_leaf=20, random_state=0)
    if kind == "lr":
        return make_pipeline(StandardScaler(), LogisticRegression(max_iter=500))
    raise ValueError(kind)


def label_rows(times, t, pages):
    """1 if page is not reused within T_HORIZON accesses after time t."""
    y = []
    for p in pages:
        lst = times[p]
        i = bisect.bisect_right(lst, t)
        dist = lst[i] - t if i < len(lst) else float("inf")
        y.append(1 if dist > T_HORIZON else 0)
    return np.array(y)


class LearnedPolicy(Policy):
    def __init__(self, model=None, online=False, label="Learned",
                 retrain_every=100, buffer_snaps=100, min_snaps=20):
        self.name = label
        self.init_model = model
        self.online = online
        self.retrain_every = retrain_every
        self.buffer_snaps = buffer_snaps
        self.min_snaps = min_snaps

    def reset(self, trace, frames):
        self.last, self.cnt, self.loaded, self.times = {}, {}, {}, {}
        self.win, self.winc = deque(), Counter()
        self.snaps = []                    # (t, pages, X)
        self.ptr = 0
        self.buf = deque(maxlen=self.buffer_snaps)
        self.since = 0
        self.model = self.init_model
        self.decisions = []                # (t, victim, confidence, X_row)

    def observe(self, t, p):
        if len(self.win) == WINDOW:
            self.winc[self.win.popleft()] -= 1
        self.win.append(p)
        self.winc[p] += 1
        self.last[p] = t
        self.cnt[p] = self.cnt.get(p, 0) + 1
        self.times.setdefault(p, []).append(t)

    def on_load(self, t, p):
        self.loaded[p] = t

    def features(self, t, pages):
        return np.array([[np.log1p(t - self.last[p]), self.winc[p],
                          np.log1p(self.cnt[p]), np.log1p(t - self.loaded[p])]
                         for p in pages])

    def _mature_and_retrain(self, t):
        while self.ptr < len(self.snaps) and self.snaps[self.ptr][0] + T_HORIZON <= t:
            ts, pages, X = self.snaps[self.ptr]
            self.buf.append((X, label_rows(self.times, ts, pages)))
            self.ptr += 1
        if self.since >= self.retrain_every and len(self.buf) >= self.min_snaps:
            X = np.vstack([b[0] for b in self.buf])
            y = np.concatenate([b[1] for b in self.buf])
            if len(set(y)) == 2:
                m = make_model("dt")
                m.fit(X, y)
                self.model = m
            self.since = 0

    def victim(self, t, cache):
        pages = list(cache)
        X = self.features(t, pages)
        if self.online:
            self.since += 1
            self._mature_and_retrain(t)
        self.snaps.append((t, pages, X))
        if self.model is None:             # fallback = LRU until a model exists
            idx, conf = int(np.argmax(X[:, 0])), None
        else:
            proba = self.model.predict_proba(X)[:, 1]
            idx = int(np.argmax(proba + 1e-6 * X[:, 0]))
            conf = float(proba[idx])
        self.decisions.append((t, pages[idx], conf, X[idx]))
        return pages[idx]


def train_static(kind, trace, frames):
    """Fit a model on eviction snapshots generated by running LRU on `trace`."""
    rec = LearnedPolicy(model=None, label="recorder")
    simulate(trace, frames, rec)
    Xs, ys = [], []
    for ts, pages, X in rec.snaps:
        Xs.append(X)
        ys.append(label_rows(rec.times, ts, pages))
    X, y = np.vstack(Xs), np.concatenate(ys)
    m = make_model(kind)
    m.fit(X, y)
    return m
